# -*- coding: utf-8 -*-
# Translations for AiFileStudio.PRO. English is the default/source language
# and lives directly in generate_pages.py's TOOLS list - this file only holds
# Hindi (hi) and Spanish (es) translations.
#
# HONESTY NOTE: this content was AI-translated, not reviewed by a native
# speaker. It should read as accurate, natural Hindi/Spanish, but a native
# speaker pass is recommended before treating it as fully final/polished -
# same principle applied to every other claim on this site.

LANGUAGES = {
    "en": {"name": "English", "native": "English"},
    "hi": {"name": "Hindi", "native": "हिन्दी"},
    "es": {"name": "Spanish", "native": "Español"},
}

# Shared UI chrome + every dynamic string main.js shows a user.
UI_STRINGS = {
    "hi": {
        # Sidebar / nav
        "site_tagline": "सुरक्षित। स्थानीय। पेशेवर।",
        "search_tools": "टूल खोजें",
        "privacy": "गोपनीयता",
        "contact": "संपर्क करें",
        "privacy_policy": "गोपनीयता नीति",
        "terms_of_service": "सेवा की शर्तें",
        "help_faq": "मदद और सामान्य प्रश्न",
        "system_status": "सिस्टम स्थिति",
        "support_dev": "डेवलपमेंट को सपोर्ट करें",
        "buy_coffee": "मुझे कॉफ़ी खिलाएं",
        "group_creative": "क्रिएटिव",
        "group_pdf": "पीडीएफ टूलकिट",
        "group_convert": "कन्वर्ट",
        "group_utils": "यूटिलिटीज़",
        "recently_used": "हाल ही में इस्तेमाल किए गए",
        "all_tools": "सभी टूल",
        "results": "परिणाम",
        "no_match": "कोई टूल नहीं मिला",
        # Page chrome
        "home": "होम",
        "upload_file": "फ़ाइल अपलोड करें",
        "upload_files": "फ़ाइलें अपलोड करें",
        "drag_drop": "फ़ाइलें यहाँ खींचें और छोड़ें, या ब्राउज़ करने के लिए क्लिक करें",
        "execute_task": "टास्क चलाएँ",
        "reset": "रीसेट",
        "more_tools": "और टूल",
        "faq_heading": "अक्सर पूछे जाने वाले प्रश्न",
        "engine_running": "इंजन चल रहा है...",
        "loading_engine": "इंजन लोड हो रहा है...",
        "close": "बंद करें",
        "download": "डाउनलोड करें",
        "downloaded": "✓ डाउनलोड हो गया",
        "footer": "© 2026 AiFileStudio.pro",
        # Contact/Terms modal
        "contact_us": "हमसे संपर्क करें",
        "terms_title": "सेवा की शर्तें",
        "terms_body": "AiFileStudio.PRO के टूल केवल वैध उद्देश्यों के लिए उपयोग करें। अधिकतर टूल (पीडीएफ मर्ज/स्प्लिट/रोटेट, रीसाइज़, JPG↔PNG, OCR, पासवर्ड जनरेशन, QR कोड) आपके ब्राउज़र में स्थानीय रूप से प्रोसेस होते हैं और हमारे सर्वर पर अपलोड नहीं किए जाते।",
        # Command palette
        "cmdk_placeholder": "टूल खोजें...",
        # Error/validation strings (main.js)
        "err_generic": "कुछ गलत हो गया। कृपया अपना इनपुट जाँचें और फिर से कोशिश करें। (विवरण ब्राउज़र कंसोल में लॉग हुआ है — F12 दबाएँ।)",
        "err_lib_load": "इस टूल के लिए ज़रूरी कॉम्पोनेंट लोड नहीं हो सका — अपना इंटरनेट कनेक्शन जाँचें, या स्क्रिप्ट ब्लॉक करने वाला कोई ऐड-ब्लॉकर/एक्सटेंशन बंद करके फिर कोशिश करें।",
        "err_pdf_preview": "इस पीडीएफ के पेज़ों का पूर्वावलोकन नहीं हो सका। ज़रूरत पड़ने पर आप अब भी पेज नंबर मैन्युअल रूप से टाइप कर सकते हैं।",
    },
    "es": {
        "site_tagline": "Seguro. Local. Profesional.",
        "search_tools": "Buscar herramientas",
        "privacy": "Privacidad",
        "contact": "Contacto",
        "privacy_policy": "Política de Privacidad",
        "terms_of_service": "Términos de Servicio",
        "help_faq": "Ayuda y Preguntas Frecuentes",
        "system_status": "Estado del Sistema",
        "support_dev": "Apoya el Desarrollo",
        "buy_coffee": "Invítame un café",
        "group_creative": "Creativo",
        "group_pdf": "Herramientas PDF",
        "group_convert": "Convertir",
        "group_utils": "Utilidades",
        "recently_used": "Usados recientemente",
        "all_tools": "Todas las herramientas",
        "results": "Resultados",
        "no_match": "No se encontraron herramientas",
        "home": "Inicio",
        "upload_file": "Subir archivo",
        "upload_files": "Subir archivos",
        "drag_drop": "Arrastra y suelta archivos aquí, o haz clic para explorar",
        "execute_task": "Ejecutar",
        "reset": "Reiniciar",
        "more_tools": "Más herramientas",
        "faq_heading": "Preguntas Frecuentes",
        "engine_running": "MOTOR EN EJECUCIÓN...",
        "loading_engine": "CARGANDO MOTOR...",
        "close": "Cerrar",
        "download": "Descargar",
        "downloaded": "✓ Descargado",
        "footer": "© 2026 AiFileStudio.pro",
        "contact_us": "Contáctanos",
        "terms_title": "Términos de Servicio",
        "terms_body": "Usa las herramientas de AiFileStudio.PRO solo para fines legales. La mayoría de las herramientas (unir/dividir/rotar PDF, redimensionar, JPG↔PNG, OCR, generación de contraseñas, códigos QR) se procesan localmente en tu navegador y no se suben a nuestros servidores.",
        "cmdk_placeholder": "Buscar herramientas...",
        "err_generic": "Algo salió mal. Comprueba tu entrada e inténtalo de nuevo. (Detalles registrados en la consola del navegador — pulsa F12.)",
        "err_lib_load": "No se pudo cargar un componente necesario para esta herramienta — comprueba tu conexión a internet, o desactiva algún bloqueador de anuncios/extensión que pueda estar bloqueando scripts, e inténtalo de nuevo.",
        "err_pdf_preview": "No se pudo generar la vista previa de las páginas de este PDF. Aún puedes escribir los números de página manualmente si lo necesitas.",
    },
}

# Per-tool content translations, keyed by mode.
# Each entry: title, subtitle, input_label, input_placeholder, about_heading,
# about_html (kept more concise than English for translation-quality reasons),
# faq (1-2 Q&A pairs).
TOOL_TRANSLATIONS = {
    "hi": {
        "ai": dict(title="एआई इमेज जनरेटर", subtitle="टेक्स्ट विवरण से इमेज बनाएं।",
            input_label="जो इमेज चाहिए उसका विवरण दें", input_placeholder="जैसे: सूर्यास्त में एक लाइटहाउस",
            about_heading="मुफ़्त एआई इमेज जनरेटर",
            about_html="<p>एक विवरण टाइप करें और सेकंडों में एक इमेज बनाएं। यह टूल आपका टेक्स्ट प्रॉम्प्ट Pollinations AI (एक थर्ड-पार्टी सर्विस) को भेजता है — यह इस साइट का इकलौता टूल है जो पूरी तरह लोकल नहीं है, इसलिए प्रॉम्प्ट में निजी जानकारी न डालें।</p>",
            faq=[("क्या मेरा प्रॉम्प्ट निजी रहता है?", "नहीं — यह टूल इमेज बनाने के लिए आपका टेक्स्ट प्रॉम्प्ट Pollinations AI को भेजता है। इसमें गोपनीय जानकारी न डालें।")]),
        "resize": dict(title="इमेज रीसाइज़र", subtitle="इमेज को लोकल रूप से रीसाइज़ करें।",
            input_label="चौड़ाई (पिक्सल में)", input_placeholder="जैसे: 800",
            about_heading="मुफ़्त लोकल इमेज रीसाइज़र",
            about_html="<p>एक या कई इमेज को अपने ब्राउज़र में ही रीसाइज़ करें — कुछ भी सर्वर पर अपलोड नहीं होता। चौड़ाई डालें, ऊँचाई अनुपात के अनुसार अपने आप सेट हो जाएगी। स्कैन की गई इमेज के लिए ब्राइटनेस/कॉन्ट्रास्ट/ब्लैक-एंड-व्हाइट विकल्प भी उपलब्ध हैं।</p>",
            faq=[("क्या रीसाइज़िंग के लिए इमेज कहीं अपलोड होती है?", "नहीं। यह पूरी तरह आपके डिवाइस पर, ब्राउज़र के कैनवस के ज़रिए होता है।")]),
        "convert": dict(title="JPG से PNG कन्वर्टर", subtitle="JPG इमेज को PNG में बदलें।",
            input_label="", input_placeholder="",
            about_heading="मुफ़्त JPG से PNG कन्वर्टर",
            about_html="<p>अपने ब्राउज़र में ही किसी JPG फ़ोटो को PNG फ़ाइल में बदलें — कोई अपलोड नहीं, कोई इंतज़ार नहीं। PNG एक लॉसलेस फॉर्मैट है, इसलिए यह लोगो, स्क्रीनशॉट या पारदर्शिता वाली इमेज के लिए बेहतर होता है।</p>",
            faq=[("क्या PNG में बदलने से इमेज में पारदर्शिता आ जाती है?", "नहीं — JPG फ़ाइलों में पारदर्शिता की जानकारी नहीं होती, इसलिए बदली गई PNG का बैकग्राउंड वैसा ही रहेगा।")]),
        "merge": dict(title="पीडीएफ मर्ज करें", subtitle="कई पीडीएफ फ़ाइलों को एक में मिलाएं।",
            input_label="", input_placeholder="",
            about_heading="मुफ़्त पीडीएफ मर्जर — लोकल रूप से पीडीएफ मिलाएं",
            about_html="<p>दो या ज़्यादा पीडीएफ चुनें और AiFileStudio उन्हें आपके चुने हुए क्रम में एक फ़ाइल में मिला देगा। सारा काम <code class=\"text-blue-400\">pdf-lib</code> लाइब्रेरी से लोकल रूप से होता है — आपकी फ़ाइलें सर्वर पर अपलोड नहीं होतीं।</p>",
            faq=[("क्या मैं कितनी भी पीडीएफ मर्ज कर सकता हूँ?", "कोई तय सीमा नहीं है, हालांकि बहुत बड़ी फ़ाइलें आपके डिवाइस की मेमोरी पर निर्भर करती हैं।")]),
        "split": dict(title="पीडीएफ स्प्लिट करें", subtitle="पीडीएफ से चुने हुए पेज निकालें।",
            input_label="निकालने के लिए पेज नंबर", input_placeholder="जैसे: 1, 3, 5",
            about_heading="मुफ़्त पीडीएफ स्प्लिटर",
            about_html="<p>किसी लंबे पीडीएफ में से ज़रूरी पेज निकालकर एक नई, छोटी फ़ाइल बनाएं। पेज नंबर डालें (कॉमा से अलग करके) और AiFileStudio उन्हीं पेजों की नई पीडीएफ बना देगा — सब कुछ आपके ब्राउज़र में।</p>",
            faq=[("क्या मैं पेजों की रेंज दे सकता हूँ, जैसे 1 से 5?", "फ़िलहाल आप कॉमा से अलग करके अलग-अलग पेज नंबर डालते हैं (जैसे 1, 2, 3, 4, 5)।")]),
        "rotate": dict(title="पीडीएफ घुमाएं", subtitle="पीडीएफ के हर पेज को 90° घुमाएं।",
            input_label="", input_placeholder="",
            about_heading="मुफ़्त पीडीएफ रोटेटर",
            about_html="<p>अगर कोई पीडीएफ स्कैन उल्टा या टेढ़ा आया है तो उसे ठीक करें। फ़ाइल अपलोड करें, AiFileStudio हर पेज को 90 डिग्री घुमा देगा — सब कुछ आपके ब्राउज़र में लोकल रूप से।</p>",
            faq=[("क्या मैं सिर्फ़ एक पेज घुमा सकता हूँ, पूरा डॉक्यूमेंट नहीं?", "फ़िलहाल नहीं — यह टूल पूरे पीडीएफ के सभी पेजों को समान रूप से घुमाता है।")]),
        "pdf": dict(title="JPG से पीडीएफ कन्वर्टर", subtitle="इमेज को एक पीडीएफ डॉक्यूमेंट में बदलें।",
            input_label="", input_placeholder="",
            about_heading="मुफ़्त JPG से पीडीएफ कन्वर्टर",
            about_html="<p>एक या कई फ़ोटो/स्कैन की गई इमेज को एक पीडीएफ डॉक्यूमेंट में बदलें। इमेज चुनें, AiFileStudio हर एक को अपने पेज पर रखेगा — यह सब <code class=\"text-blue-400\">jsPDF</code> लाइब्रेरी से लोकल रूप से होता है।</p>",
            faq=[("कौन-कौन से इमेज फॉर्मैट पीडीएफ में बदले जा सकते हैं?", "JPG/JPEG सबसे अच्छा काम करता है; ज़्यादातर सामान्य इमेज फॉर्मैट भी काम करेंगे।")]),
        "deletepages": dict(title="पीडीएफ पेज हटाएं", subtitle="पीडीएफ से चुने हुए पेज हटाएं।",
            input_label="हटाने के लिए पेज नंबर", input_placeholder="जैसे: 2, 4, 7",
            about_heading="मुफ़्त पीडीएफ पेज हटाने का टूल",
            about_html="<p>पीडीएफ से एक या ज़्यादा पेज हटाएं, बाकी डॉक्यूमेंट को बिना छेड़े। फ़ाइल अपलोड करें और विज़ुअल पेज पिकर में जो पेज हटाने हैं उन पर क्लिक करें — सब कुछ <code class=\"text-blue-400\">pdf-lib</code> से लोकल रूप से होता है।</p>",
            faq=[("क्या मैं सभी पेज हटा सकता हूँ?", "नहीं — कम से कम एक पेज बचा रहना चाहिए, वरना पीडीएफ खाली हो जाएगी।")]),
        "extractpages": dict(title="पीडीएफ पेज निकालें", subtitle="चुने हुए पेजों को अलग-अलग फ़ाइलों में सेव करें।",
            input_label="निकालने के लिए पेज (रेंज या लिस्ट)", input_placeholder="जैसे: 2-5 या 1, 3, 5",
            about_heading="मुफ़्त पीडीएफ पेज एक्सट्रैक्ट टूल",
            about_html="<p>पीडीएफ से पेज निकालें और हर पेज को अपनी अलग पीडीएफ फ़ाइल के रूप में पाएं, ZIP में। यह <a href=\"split-pdf/\" class=\"text-blue-500 underline\">पीडीएफ स्प्लिट</a> से अलग है, जो चुने हुए पेजों को एक ही नई फ़ाइल में जोड़ता है।</p>",
            faq=[("यह पीडीएफ स्प्लिट से कैसे अलग है?", "स्प्लिट टूल चुने हुए पेजों को एक फ़ाइल में जोड़ता है। एक्सट्रैक्ट पेजेस हर पेज को अलग फ़ाइल के रूप में देता है, ZIP में।")]),
        "reorder": dict(title="पीडीएफ पेज क्रम बदलें", subtitle="पीडीएफ के पेजों का क्रम बदलें।",
            input_label="नया पेज क्रम", input_placeholder="जैसे: 3, 1, 2",
            about_heading="मुफ़्त पीडीएफ पेज रीऑर्डर टूल",
            about_html="<p>पीडीएफ पेजों को नए क्रम में सजाएं। फ़ाइल अपलोड करें, फिर विज़ुअल पिकर में पेजों पर उसी क्रम में क्लिक करें जिस क्रम में आप उन्हें चाहते हैं — हर क्लिक से उस पेज पर एक नंबर दिख जाएगा।</p>",
            faq=[("अगर मुझे सिर्फ़ एक पेज खिसकाना है तो?", "फिर भी हर पेज को पूरे नए क्रम में क्लिक करना होगा — जैसे 5 पेज की पीडीएफ में आखिरी पेज को आगे लाने के लिए, पहले उसी पर क्लिक करें, फिर बाकी पेजों पर क्रम से।")]),
        "pagenumbers": dict(title="पीडीएफ में पेज नंबर जोड़ें", subtitle="हर पेज पर क्रमिक पेज नंबर लगाएं।",
            input_label="", input_placeholder="",
            about_heading="मुफ़्त पीडीएफ पेज नंबरिंग टूल",
            about_html="<p>पीडीएफ के हर पेज के नीचे बीच में एक पेज नंबर लगाएं — प्रिंट करने या जमा करने से पहले उपयोगी। नंबरिंग 1 से शुरू होकर पूरे डॉक्यूमेंट में चलती है, सब कुछ <code class=\"text-blue-400\">pdf-lib</code> से लोकल रूप से।</p>",
            faq=[("क्या मैं पेज नंबर की जगह बदल सकता हूँ?", "फ़िलहाल नहीं — यह हमेशा हर पेज के नीचे बीच में लगता है।")]),
        "watermark": dict(title="पीडीएफ वॉटरमार्क", subtitle="हर पेज पर तिरछा टेक्स्ट लगाएं।",
            input_label="वॉटरमार्क टेक्स्ट", input_placeholder="जैसे: गोपनीय या ड्राफ्ट",
            about_heading="मुफ़्त पीडीएफ वॉटरमार्क टूल",
            about_html="<p>पीडीएफ के हर पेज पर एक हल्का, तिरछा टेक्स्ट वॉटरमार्क लगाएं — जैसे \"गोपनीय\" या आपकी कंपनी का नाम। यह सब <code class=\"text-blue-400\">pdf-lib</code> से लोकल रूप से होता है।</p>",
            faq=[("क्या वॉटरमार्क का रंग या साइज़ बदला जा सकता है?", "फ़िलहाल इंटरफ़ेस से नहीं — वॉटरमार्क हमेशा हल्के ग्रे रंग में, 45 डिग्री पर आता है।")]),
        "crop": dict(title="पीडीएफ क्रॉप करें", subtitle="पीडीएफ के हर पेज के किनारे काटें।",
            input_label="किनारे से कितना काटना है: ऊपर, दाएं, नीचे, बाएं (%)", input_placeholder="जैसे: 5, 5, 5, 5",
            about_heading="मुफ़्त पीडीएफ क्रॉप टूल",
            about_html="<p>पीडीएफ के हर पेज से अतिरिक्त मार्जिन हटाएं — हर तरफ से कितना प्रतिशत काटना है यह बताकर। यह <code class=\"text-blue-400\">pdf-lib</code> से लोकल रूप से क्रॉप बॉक्स एडजस्ट करता है।</p>",
            faq=[("क्या हर तरफ अलग मात्रा में क्रॉप हो सकता है?", "हाँ — आपके डाले चार नंबर ऊपर, दाएं, नीचे और बाएं के लिए अलग-अलग होते हैं।")]),
        "compress": dict(title="पीडीएफ कंप्रेस करें", subtitle="JPEG इमेज को फिर से कंप्रेस करके पीडीएफ छोटा करें।",
            input_label="इमेज क्वालिटी (1-100, कम = छोटी फ़ाइल)", input_placeholder="जैसे: 60",
            about_heading="मुफ़्त पीडीएफ कंप्रेसर",
            about_html="<p><strong>ईमानदार सीमा:</strong> यह टूल पीडीएफ के अंदर मौजूद JPEG इमेज को ढूंढकर आपकी चुनी क्वालिटी पर दोबारा एनकोड करता है, साथ में स्ट्रक्चरल कंप्रेशन भी लगाता है। अगर इमेज किसी और फॉर्मैट में हैं, तो सिर्फ़ स्ट्रक्चरल कंप्रेशन का ही फ़ायदा मिलेगा।</p>",
            faq=[("मेरी पीडीएफ ज़्यादा छोटी क्यों नहीं हुई?", "यह टूल सिर्फ़ JPEG इमेज को दोबारा कंप्रेस करता है। अगर आपकी पीडीएफ की इमेज किसी और फॉर्मैट में हैं, तो सिर्फ़ स्ट्रक्चरल कंप्रेशन का फ़ायदा मिलेगा।")]),
        "viewer": dict(title="पीडीएफ व्यूअर", subtitle="पीडीएफ के पेज सीधे ब्राउज़र में देखें।",
            input_label="", input_placeholder="",
            about_heading="मुफ़्त ऑनलाइन पीडीएफ व्यूअर",
            about_html="<p><code class=\"text-blue-400\">pdf.js</code> से पीडीएफ को सीधे ब्राउज़र में खोलें और देखें — कोई सॉफ़्टवेयर इंस्टॉल नहीं, कोई अकाउंट नहीं, फ़ाइल सर्वर पर अपलोड नहीं होती।</p>",
            faq=[("क्या मैं यहाँ पीडीएफ एडिट कर सकता हूँ?", "नहीं — यह टूल सिर्फ़ देखने के लिए है। एडिट करने के लिए हमारे बाकी पीडीएफ टूल इस्तेमाल करें।")]),
        "imgcompress": dict(title="इमेज कंप्रेसर", subtitle="क्वालिटी एडजस्ट करके इमेज की फ़ाइल साइज़ घटाएं।",
            input_label="क्वालिटी (1-100, कम = छोटी फ़ाइल)", input_placeholder="जैसे: 70",
            about_heading="मुफ़्त लोकल इमेज कंप्रेसर",
            about_html="<p>इमेज को आपकी चुनी क्वालिटी पर JPEG के रूप में दोबारा एनकोड करके फ़ाइल साइज़ घटाएं। यह प्रोसेसिंग HTML5 कैनवस पर लोकल रूप से होती है — इमेज कहीं अपलोड नहीं होतीं।</p>",
            faq=[("क्या इससे इमेज का साइज़ (डाइमेंशन) भी बदलता है?", "नहीं — सिर्फ़ कंप्रेशन क्वालिटी बदलती है, डाइमेंशन वही रहते हैं।")]),
        "favicon": dict(title="फेविकॉन जनरेटर", subtitle="इमेज से फेविकॉन के सभी साइज़ बनाएं।",
            input_label="", input_placeholder="",
            about_heading="मुफ़्त फेविकॉन जनरेटर",
            about_html="<p>एक लोगो अपलोड करें और सभी ज़रूरी फेविकॉन साइज़ (16×16 से 512×512 तक) एक ZIP में पाएं, साथ में एक तैयार <code class=\"text-blue-400\">site.webmanifest</code> फ़ाइल भी।</p>",
            faq=[("सोर्स इमेज कितनी बड़ी होनी चाहिए?", "कम से कम 512×512 पिक्सल की एक चौकोर इमेज सबसे अच्छा रिज़ल्ट देती है।")]),
        "barcode": dict(title="बारकोड जनरेटर", subtitle="टेक्स्ट या नंबर से स्कैन होने वाला बारकोड बनाएं।",
            input_label="एनकोड करने के लिए टेक्स्ट या नंबर", input_placeholder="जैसे: 123456789012",
            about_heading="मुफ़्त बारकोड जनरेटर",
            about_html="<p>किसी भी टेक्स्ट या नंबर से CODE128 बारकोड बनाएं, <code class=\"text-blue-400\">JsBarcode</code> लाइब्रेरी से लोकल रूप से — कुछ भी कहीं नहीं भेजा जाता।</p>",
            faq=[("क्या यह QR कोड जैसा ही है?", "नहीं — यह पारंपरिक धारीदार (1D) बारकोड है। QR कोड के लिए हमारा QR जनरेटर इस्तेमाल करें।")]),
        "bgremove": dict(title="बैकग्राउंड रिमूवर", subtitle="किसी व्यक्ति की फ़ोटो का बैकग्राउंड हटाएं या बदलें।",
            input_label="", input_placeholder="",
            about_heading="मुफ़्त बैकग्राउंड रिमूवर (व्यक्ति की फ़ोटो के लिए)",
            about_html="<p><strong>ईमानदार सीमा:</strong> यह टूल Google के MediaPipe मॉडल से किसी फ़ोटो में व्यक्ति को बैकग्राउंड से अलग करता है, आपके ब्राउज़र में। यह खासतौर पर व्यक्तियों की फ़ोटो के लिए बना है — किसी और चीज़ (सामान, जानवर) पर नतीजे अच्छे नहीं आ सकते।</p>",
            faq=[("क्या इसे सामान या जानवरों की फ़ोटो पर इस्तेमाल कर सकते हैं?", "भरोसेमंद तरीके से नहीं — यह टूल इंसानों की फ़ोटो के लिए ट्रेन किया गया है।")]),
        "txt2pdf": dict(title="TXT से पीडीएफ कन्वर्टर", subtitle="प्लेन टेक्स्ट से डाउनलोड होने वाली पीडीएफ बनाएं।",
            input_label="अपना टेक्स्ट पेस्ट करें", input_placeholder="यहाँ टेक्स्ट पेस्ट या टाइप करें...",
            about_heading="मुफ़्त TXT से पीडीएफ कन्वर्टर",
            about_html="<p>प्लेन टेक्स्ट पेस्ट करें और एक फॉर्मैटेड, डाउनलोड होने वाली पीडीएफ पाएं — कोई फ़ाइल अपलोड की ज़रूरत नहीं। यह सब <code class=\"text-blue-400\">jsPDF</code> से आपके ब्राउज़र में होता है।</p>",
            faq=[("क्या इससे बोल्ड या बुलेट पॉइंट जैसी फॉर्मेटिंग बनी रहती है?", "नहीं — यह सिर्फ़ प्लेन टेक्स्ट कन्वर्ट करता है।")]),
        "html2pdf": dict(title="HTML से पीडीएफ कन्वर्टर", subtitle="HTML मार्कअप को डाउनलोड होने वाली पीडीएफ में बदलें।",
            input_label="अपना HTML पेस्ट करें", input_placeholder="<h1>नमस्ते</h1><p>कुछ कंटेंट...</p>",
            about_heading="मुफ़्त HTML से पीडीएफ कन्वर्टर",
            about_html="<p>HTML का एक टुकड़ा पेस्ट करें, AiFileStudio उसे रेंडर करके एक इमेज के रूप में कैप्चर करेगा और पीडीएफ में डाल देगा। आपका पेस्ट किया HTML एक सैंडबॉक्स्ड फ्रेम में रेंडर होता है जहाँ स्क्रिप्ट चलना बंद रहता है।</p>",
            faq=[("क्या नतीजे में पीडीएफ का टेक्स्ट सर्च किया जा सकता है?", "नहीं — क्योंकि यह एक कैप्चर की गई इमेज के रूप में रेंडर होता है, टेक्स्ट सिलेक्ट या सर्च नहीं किया जा सकता।")]),
        "ocr": dict(title="OCR: इमेज से टेक्स्ट", subtitle="इमेज या स्कैन किए पेजों से टेक्स्ट निकालें।",
            input_label="", input_placeholder="",
            about_heading="मुफ़्त OCR टूल — इमेज से टेक्स्ट",
            about_html="<p><strong>Tesseract.js</strong> से किसी फ़ोटो या स्कैन की गई इमेज से एडिटेबल टेक्स्ट निकालें, आपके ब्राउज़र में। स्कैन की गई डॉक्यूमेंट के लिए पहले ब्राइटनेस/कॉन्ट्रास्ट स्लाइडर आज़माएं — साफ़ इनपुट से बेहतर नतीजे मिलते हैं।</p>",
            faq=[("OCR कितना सटीक है?", "यह इमेज की क्वालिटी पर निर्भर करता है — साफ़, अच्छी रोशनी वाला टेक्स्ट सबसे बेहतर पहचाना जाता है।")]),
        "pass": dict(title="पासवर्ड जनरेटर", subtitle="लोकल रूप से मज़बूत, रैंडम पासवर्ड बनाएं।",
            input_label="", input_placeholder="",
            about_heading="मुफ़्त सुरक्षित पासवर्ड जनरेटर",
            about_html="<p>आपके ब्राउज़र के बिल्ट-इन क्रिप्टोग्राफ़िक रैंडम नंबर जनरेटर से एक मज़बूत, रैंडम पासवर्ड बनाएं। कुछ भी कहीं नहीं भेजा जाता — पासवर्ड सिर्फ़ आपके डिवाइस पर बनता और दिखता है।</p>",
            faq=[("क्या यह पासवर्ड जनरेटर सच में सुरक्षित है?", "हाँ — यह Web Crypto API के क्रिप्टोग्राफ़िक रूप से सुरक्षित रैंडम वैल्यू इस्तेमाल करता है, पूरी तरह लोकल रूप से।")]),
        "qr": dict(title="QR कोड जनरेटर", subtitle="लिंक या टेक्स्ट को QR कोड में बदलें।",
            input_label="एनकोड करने के लिए टेक्स्ट या URL", input_placeholder="जैसे: https://example.com",
            about_heading="मुफ़्त QR कोड जनरेटर",
            about_html="<p>किसी भी लिंक या छोटे टेक्स्ट को तुरंत, आपके ब्राउज़र में ही स्कैन होने वाले QR कोड में बदलें। बिज़नेस कार्ड, प्रिंटेड फ़्लायर या Wi-Fi शेयर करने के लिए उपयोगी।</p>",
            faq=[("क्या मैं QR कोड को इमेज के रूप में डाउनलोड कर सकता हूँ?", "बने हुए QR कोड पर राइट-क्लिक करें (मोबाइल पर लॉन्ग-प्रेस) और 'इमेज सेव करें' चुनें।")]),
    },
    "es": {
        "ai": dict(title="Generador de Imágenes con IA", subtitle="Crea imágenes a partir de descripciones de texto.",
            input_label="Describe la imagen que quieres", input_placeholder="ej. un faro al atardecer, estilo pintura al óleo",
            about_heading="Generador de Imágenes con IA Gratis",
            about_html="<p>Escribe una descripción y genera una imagen en segundos. Esta herramienta envía tu texto a Pollinations AI, un servicio de terceros — es la única herramienta de este sitio que no es totalmente local, así que evita escribir información privada en el prompt.</p>",
            faq=[("¿Es privado mi prompt?", "No — a diferencia de nuestras otras herramientas, el generador de arte con IA envía tu prompt a Pollinations AI para crear la imagen.")]),
        "resize": dict(title="Redimensionador de Imágenes", subtitle="Redimensiona imágenes localmente.",
            input_label="Ancho objetivo en píxeles", input_placeholder="ej. 800",
            about_heading="Redimensionador de Imágenes Local Gratis",
            about_html="<p>Redimensiona una o varias imágenes a la vez, totalmente en tu navegador — nada se sube a un servidor. Introduce el ancho deseado y la altura se ajusta proporcionalmente. Para documentos escaneados, prueba los ajustes de brillo y contraste.</p>",
            faq=[("¿Se suben mis imágenes a algún servidor?", "No. El redimensionado ocurre completamente en tu dispositivo mediante la API de canvas de HTML5.")]),
        "convert": dict(title="Convertidor de JPG a PNG", subtitle="Convierte imágenes JPG a formato PNG, localmente.",
            input_label="", input_placeholder="",
            about_heading="Convertidor Gratis de JPG a PNG",
            about_html="<p>Convierte una foto JPG a un archivo PNG directamente en tu navegador — sin subir archivos, sin esperas. PNG es un formato sin pérdida, ideal para logos, capturas de pantalla o gráficos con transparencia.</p>",
            faq=[("¿La conversión a PNG añade transparencia a mi JPG?", "No — los archivos JPG no guardan información de transparencia, así que el PNG resultante tendrá el mismo fondo sólido.")]),
        "merge": dict(title="Unir PDF", subtitle="Combina varios archivos PDF en uno.",
            input_label="", input_placeholder="",
            about_heading="Unificador de PDF Gratis — Combina PDFs Localmente",
            about_html="<p>Selecciona dos o más PDFs y AiFileStudio los combinará en un solo documento, en el orden en que los seleccionaste. Todo se procesa localmente con <code class=\"text-blue-400\">pdf-lib</code> — tus archivos nunca se suben a un servidor.</p>",
            faq=[("¿Hay un límite de PDFs que puedo unir?", "No hay límite fijo, aunque archivos muy grandes dependen de la memoria disponible en tu dispositivo.")]),
        "split": dict(title="Dividir PDF", subtitle="Extrae páginas específicas de un PDF.",
            input_label="Números de página a extraer", input_placeholder="ej. 1, 3, 5",
            about_heading="Divisor de PDF Gratis",
            about_html="<p>Extrae páginas específicas de un PDF largo y guárdalas como un documento nuevo más pequeño. Introduce los números de página (separados por comas) y AiFileStudio crea un nuevo PDF con esas páginas, en tu navegador.</p>",
            faq=[("¿Puedo extraer un rango de páginas, como 1 a 5?", "Actualmente introduces números de página individuales separados por comas (ej. 1, 2, 3, 4, 5).")]),
        "rotate": dict(title="Rotar PDF", subtitle="Rota cada página de un PDF 90°.",
            input_label="", input_placeholder="",
            about_heading="Rotador de PDF Gratis",
            about_html="<p>Corrige un PDF que se escaneó de lado o al revés. Sube el archivo y AiFileStudio rota cada página 90 grados — todo procesado localmente en tu navegador.</p>",
            faq=[("¿Puedo rotar solo una página en lugar de todo el documento?", "No actualmente — esta herramienta rota todas las páginas del PDF en la misma cantidad.")]),
        "pdf": dict(title="Convertidor de JPG a PDF", subtitle="Convierte imágenes en un solo documento PDF.",
            input_label="", input_placeholder="",
            about_heading="Convertidor Gratis de JPG a PDF",
            about_html="<p>Convierte una o varias fotos o imágenes escaneadas en un solo documento PDF. Selecciona tus imágenes y AiFileStudio coloca cada una en su propia página, usando la librería <code class=\"text-blue-400\">jsPDF</code> localmente.</p>",
            faq=[("¿Qué formatos de imagen puedo convertir a PDF?", "JPG/JPEG funciona mejor; la mayoría de formatos de imagen comunes también funcionarán.")]),
        "deletepages": dict(title="Eliminar Páginas de PDF", subtitle="Elimina páginas específicas de un PDF.",
            input_label="Números de página a eliminar", input_placeholder="ej. 2, 4, 7",
            about_heading="Herramienta Gratis para Eliminar Páginas de PDF",
            about_html="<p>Elimina una o más páginas de un PDF sin tocar el resto del documento. Sube un PDF y haz clic en las páginas que quieres eliminar en el selector visual — todo procesado localmente con <code class=\"text-blue-400\">pdf-lib</code>.</p>",
            faq=[("¿Puedo eliminar todas las páginas?", "No — al menos una página debe permanecer, de lo contrario el PDF quedaría vacío.")]),
        "extractpages": dict(title="Extraer Páginas de PDF", subtitle="Guarda páginas específicas como archivos PDF separados.",
            input_label="Páginas a extraer (rango o lista)", input_placeholder="ej. 2-5 o 1, 3, 5",
            about_heading="Herramienta Gratis para Extraer Páginas de PDF",
            about_html="<p>Extrae páginas de un PDF y guarda cada una como su propio archivo PDF, en un ZIP. Esto es diferente de <a href=\"split-pdf/\" class=\"text-blue-500 underline\">Dividir PDF</a>, que combina las páginas seleccionadas en un solo documento.</p>",
            faq=[("¿Cómo se diferencia esto de Dividir PDF?", "Dividir PDF combina las páginas elegidas en un documento. Extraer Páginas entrega cada página como su propio archivo PDF, en un ZIP.")]),
        "reorder": dict(title="Reordenar Páginas de PDF", subtitle="Cambia el orden de las páginas de un PDF.",
            input_label="Nuevo orden de páginas", input_placeholder="ej. 3, 1, 2",
            about_heading="Herramienta Gratis para Reordenar Páginas de PDF",
            about_html="<p>Reorganiza las páginas de un PDF en un nuevo orden. Sube un PDF, luego haz clic en sus páginas en el selector visual, en el orden que quieras — cada clic marca esa página con un número.</p>",
            faq=[("¿Qué pasa si solo quiero mover una página?", "Debes hacer clic en todas las páginas en el nuevo orden completo — por ejemplo, en un PDF de 5 páginas, mover la última al principio significa hacer clic en ella primero, luego en las demás en orden.")]),
        "pagenumbers": dict(title="Añadir Números de Página a PDF", subtitle="Estampa números de página secuenciales en cada página.",
            input_label="", input_placeholder="",
            about_heading="Herramienta Gratis para Añadir Números de Página a PDF",
            about_html="<p>Estampa un número de página en la parte inferior central de cada página de un PDF — útil antes de imprimir o entregar un documento largo. La numeración empieza en 1, procesada localmente con <code class=\"text-blue-400\">pdf-lib</code>.</p>",
            faq=[("¿Puedo elegir dónde aparecen los números de página?", "Actualmente se colocan en la parte inferior central de cada página.")]),
        "watermark": dict(title="Marca de Agua en PDF", subtitle="Estampa texto en diagonal en cada página.",
            input_label="Texto de la marca de agua", input_placeholder="ej. CONFIDENCIAL o BORRADOR",
            about_heading="Herramienta Gratis de Marca de Agua para PDF",
            about_html="<p>Estampa una marca de agua de texto semitransparente y diagonal — como \"CONFIDENCIAL\" o el nombre de tu empresa — en cada página de un PDF, procesado localmente con <code class=\"text-blue-400\">pdf-lib</code>.</p>",
            faq=[("¿Puedo cambiar el color o tamaño de la marca de agua?", "Aún no desde la interfaz — la marca de agua aparece en gris semitransparente, a 45 grados.")]),
        "crop": dict(title="Recortar PDF", subtitle="Recorta los márgenes de cada página de un PDF.",
            input_label="Márgenes a recortar: arriba, derecha, abajo, izquierda (%)", input_placeholder="ej. 5, 5, 5, 5",
            about_heading="Herramienta Gratis para Recortar PDF",
            about_html="<p>Recorta el exceso de márgenes de cada página de un PDF indicando cuánto cortar de cada lado, como porcentaje. Esto ajusta la caja de recorte del PDF localmente con <code class=\"text-blue-400\">pdf-lib</code>.</p>",
            faq=[("¿Puedo recortar cada lado en una cantidad diferente?", "Sí — los cuatro números que introduces corresponden a arriba, derecha, abajo e izquierda de forma independiente.")]),
        "compress": dict(title="Comprimir PDF", subtitle="Reduce un PDF recomprimiendo sus imágenes JPEG.",
            input_label="Calidad de imagen (1-100, menor = archivo más pequeño)", input_placeholder="ej. 60",
            about_heading="Compresor de PDF Gratis",
            about_html="<p><strong>Alcance honesto:</strong> esta herramienta busca imágenes JPEG dentro del PDF y las recodifica a menor calidad, además de aplicar compresión estructural. Si las imágenes están en otro formato, solo verás la ganancia de la compresión estructural.</p>",
            faq=[("¿Por qué mi PDF no se redujo mucho?", "Esta herramienta solo recomprime imágenes JPEG. Si las imágenes de tu PDF están en otro formato, solo obtendrás las ganancias de la compresión estructural.")]),
        "viewer": dict(title="Visor de PDF", subtitle="Visualiza las páginas de un PDF directamente en tu navegador.",
            input_label="", input_placeholder="",
            about_heading="Visor de PDF Online Gratis",
            about_html="<p>Abre y visualiza un PDF directamente en tu navegador usando <code class=\"text-blue-400\">pdf.js</code> — sin instalar software, sin cuenta, y el archivo no se sube a un servidor.</p>",
            faq=[("¿Puedo editar el PDF aquí?", "No — esta herramienta es solo de visualización. Usa nuestras otras herramientas de PDF para modificarlo.")]),
        "imgcompress": dict(title="Compresor de Imágenes", subtitle="Reduce el tamaño de archivo de imagen ajustando la calidad.",
            input_label="Calidad (1-100, menor = archivo más pequeño)", input_placeholder="ej. 70",
            about_heading="Compresor de Imágenes Local Gratis",
            about_html="<p>Reduce el tamaño de archivo de una imagen recodificándola como JPEG con la calidad que elijas. El procesamiento ocurre localmente en el canvas de HTML5 — las imágenes no se suben a ningún lado.</p>",
            faq=[("¿Esto también redimensiona mi imagen?", "No — las dimensiones se mantienen igual, solo cambia la calidad de compresión.")]),
        "favicon": dict(title="Generador de Favicon", subtitle="Convierte una imagen en un conjunto completo de tamaños de favicon.",
            input_label="", input_placeholder="",
            about_heading="Generador de Favicon Gratis",
            about_html="<p>Sube un logo y obtén un conjunto completo de tamaños de favicon (de 16×16 a 512×512) en un ZIP, junto con un archivo <code class=\"text-blue-400\">site.webmanifest</code> listo para usar.</p>",
            faq=[("¿Qué tamaño de imagen de origen debo subir?", "Una imagen cuadrada de al menos 512×512 píxeles da los mejores resultados.")]),
        "barcode": dict(title="Generador de Códigos de Barras", subtitle="Convierte texto o números en un código de barras escaneable.",
            input_label="Texto o número a codificar", input_placeholder="ej. 123456789012",
            about_heading="Generador de Códigos de Barras Gratis",
            about_html="<p>Genera un código de barras CODE128 a partir de cualquier texto o número, renderizado localmente con la librería <code class=\"text-blue-400\">JsBarcode</code> — nada de lo que escribes se envía a ningún lado.</p>",
            faq=[("¿Es esto lo mismo que un código QR?", "No — este es el formato tradicional de barras 1D (CODE128). Para códigos QR, usa nuestro Generador de Códigos QR.")]),
        "bgremove": dict(title="Eliminador de Fondo", subtitle="Elimina o reemplaza el fondo de una foto de una persona.",
            input_label="", input_placeholder="",
            about_heading="Eliminador de Fondo Gratis (Fotos de Personas)",
            about_html="<p><strong>Alcance honesto:</strong> esta herramienta usa el modelo Selfie Segmentation de MediaPipe de Google, ejecutándose localmente, para separar a una persona del fondo de una foto. Está diseñada específicamente para fotos con personas — los resultados en otros sujetos pueden ser impredecibles.</p>",
            faq=[("¿Funcionará con fotos de objetos o animales?", "No de forma confiable — esta herramienta está basada en un modelo de segmentación de personas.")]),
        "txt2pdf": dict(title="Convertidor de TXT a PDF", subtitle="Convierte texto plano en un PDF descargable.",
            input_label="Pega tu texto", input_placeholder="Pega o escribe tu texto aquí...",
            about_heading="Convertidor Gratis de TXT a PDF",
            about_html="<p>Pega texto plano y obtén un PDF formateado y descargable — no necesitas subir ningún archivo. Todo ocurre con <code class=\"text-blue-400\">jsPDF</code> en tu navegador.</p>",
            faq=[("¿Esto conserva el formato como negrita o viñetas?", "No — esta herramienta convierte solo texto plano.")]),
        "html2pdf": dict(title="Convertidor de HTML a PDF", subtitle="Convierte marcado HTML en un PDF descargable.",
            input_label="Pega tu HTML", input_placeholder="<h1>Hola</h1><p>Algo de contenido...</p>",
            about_heading="Convertidor Gratis de HTML a PDF",
            about_html="<p>Pega un fragmento de HTML y AiFileStudio lo renderiza, lo captura como imagen y lo coloca en un PDF descargable. Tu HTML se renderiza dentro de un marco aislado (sandbox) con los scripts desactivados.</p>",
            faq=[("¿El texto del PDF resultante es buscable?", "No — al ser una imagen capturada, el texto no es seleccionable ni buscable.")]),
        "ocr": dict(title="OCR: Imagen a Texto", subtitle="Extrae texto de imágenes o páginas escaneadas.",
            input_label="", input_placeholder="",
            about_heading="Herramienta OCR Gratis — Imagen a Texto",
            about_html="<p>Extrae texto editable de una foto o imagen escaneada usando <strong>Tesseract.js</strong>, en tu navegador. Para documentos escaneados, prueba primero los ajustes de brillo y contraste — una entrada más clara suele dar mejores resultados.</p>",
            faq=[("¿Qué tan preciso es el OCR?", "Depende mucho de la calidad de la imagen — el texto claro y bien iluminado se reconoce mejor.")]),
        "pass": dict(title="Generador de Contraseñas", subtitle="Genera contraseñas fuertes y aleatorias localmente.",
            input_label="", input_placeholder="",
            about_heading="Generador de Contraseñas Seguras Gratis",
            about_html="<p>Genera una contraseña fuerte y aleatoria usando el generador de números aleatorios criptográficamente seguro de tu navegador. Nada se envía a ningún lado — la contraseña se genera y muestra solo en tu dispositivo.</p>",
            faq=[("¿Este generador de contraseñas es realmente seguro?", "Sí — usa valores aleatorios criptográficamente seguros de la Web Crypto API, generados localmente.")]),
        "qr": dict(title="Generador de Códigos QR", subtitle="Convierte un enlace o texto en un código QR.",
            input_label="Texto o URL a codificar", input_placeholder="ej. https://example.com",
            about_heading="Generador de Códigos QR Gratis",
            about_html="<p>Convierte cualquier enlace o texto corto en un código QR escaneable, generado al instante en tu navegador. Útil para tarjetas de presentación, folletos impresos o compartir Wi-Fi.</p>",
            faq=[("¿Puedo descargar el código QR como imagen?", "Haz clic derecho (o mantén presionado en móvil) sobre el código QR generado y elige 'Guardar imagen'.")]),
    },
}
